language: php
php:
- 5.6
- 5.5
install:
- composer install --no-interaction --prefer-source
script:
- ./vendor/bin/phing
deploy:
  provider: heroku
  api_key:
    secure: VccBuoFubIXT3Q/KKCuzfgw6ntT2NLcUkPv3UzOSqhKVqfivPO2s+22yOWcysUfYSaYcYpemKZ+XtsnAn7jpqKc70Wok7uQs6FsKD1XjonUqxM2QrploqdS4H9zcFpF50b462HfV6SdCvoDutTpUBtPiZ63rQtVRfRfyChO+fVs=
  app: hrphp-widgets-api-1
  on:
    branch: 1.x.x
    repo: hrphp/widgets-api
    php: 5.6
